# Generated by Django 5.2.3 on 2025-06-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='pcs',
            field=models.IntegerField(default=1),
        ),
    ]
