# Generated by Django 5.2.3 on 2025-06-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_shipments_pcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
