# Generated by Django 5.2.3 on 2025-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_client_client_name_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
