# Generated by Django 5.2.3 on 2025-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_shipments_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
