# Generated by Django 5.2.3 on 2025-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_shipments_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contact_person',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
