# Generated by Django 5.2.3 on 2025-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_provider_contact_person_provider_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
