# Generated by Django 5.2.3 on 2025-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
