# Generated by Django 5.2.3 on 2025-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_client_email_alter_provider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
