# Generated by Django 5.2.3 on 2025-06-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
    ]
