# Generated by Django 5.2.3 on 2025-06-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_shipments_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='client_name',
        ),
    ]
