# Generated by Django 5.2.3 on 2025-06-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_name_provider_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='client_name',
            new_name='name',
        ),
    ]
