# Generated by Django 5.2.3 on 2025-06-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_client_name_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.provider'),
        ),
    ]
