# Generated by Django 5.2.3 on 2025-06-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_shipments_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fuel_surcharge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('bill_period_from', models.DateField()),
                ('bill_period_to', models.DateField()),
                ('additional_charges', models.IntegerField(default=0)),
                ('gst_rate', models.IntegerField(default=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('shipments', models.ManyToManyField(to='myapp.shipments')),
            ],
        ),
    ]
