# Generated by Django 5.2.3 on 2025-06-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_client_fuel_surcharge_percent_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fuel_surcharge_percent',
            new_name='fuel_charges',
        ),
    ]
