# Generated by Django 5.2.3 on 2025-06-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_fuel_surcharge_percent_client_fuel_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fuel_charges',
            new_name='fuel_surcharge_percent',
        ),
    ]
