# Generated by Django 5.2.3 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_bill_fuel_charge_bill_gst_amount_bill_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fuel_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
